$(document).ready(function(){
    $('#title').click(function(){
        $('#list').fadeIn();
        $('#about').fadeOut();
        $('.c1').fadeIn();
        $('.c2').fadeIn();
        $('.c3').fadeIn();
    })
    $('#abtubtn').click(function(){
        $('#about').fadeIn();
        $('#about').css({
            display:'grid'
        });
        $('#access').fadeOut();
        $('#list').fadeOut();
    })
    $('#accebtn').click(function(){
        $('#access').fadeIn();
        $('#access').css({
            display:'grid'
        });
        $('#about').fadeOut();
        $('#list').fadeOut();
    })
    $('#c1ctrl').click(function(){
        $('.c1').fadeIn();
        $('.c2').fadeOut();
        $('.c3').fadeOut();
    })
    $('#c2ctrl').click(function(){
        $('.c1').fadeOut();
        $('.c2').fadeIn();
        $('.c3').fadeOut();
    })
    $('#c3ctrl').click(function(){
        $('.c1').fadeOut();
        $('.c2').fadeOut();
        $('.c3').fadeIn();
    })
})